version: '3.8'
services:
  metric-server:
    build: ./metric-server
    ports:
      - "8000:8000"
    env_file:
      - ./metric-server/.env

  model-server:
    build: ./model-server
    ports:
      - "8001:8001"
    env_file:
      - ./model-server/.env

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./promethues/promethues.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus


volumes:
  grafana_data: