version: '3.8'
services:
  metric-server:
    build: ./metric-server
    # ports:
    #   - "8000:8000"
    expose:
      - "9000"
    env_file:
      - ./metric-server/.env

  model-server:
    build: ./model-server
    expose:
      - "8001"
    env_file:
      - ./model-server/.env
  api-gateway:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - model-server

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./promethues/promethues.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus


volumes:
  grafana_data: